name: Update Bike Data
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Install R packages
        run: |
          R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'ggplot2', 'lubridate', 'knitr', 'tidyr', 'viridis'), repos = 'https://cloud.r-project.org', dependencies = TRUE)"
          
      - name: Verify installations
        run: |
          R -e "installed.packages()[, c('Package', 'Version')]"
          R -e "library(httr)"

      - name: Run R script
        run: Rscript update_report.R

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update bike share dashboard"
          title: "Update bike share dashboard"
          body: "Automated data update"
          branch: "auto/update-bike-${{ github.run_id }}"
          base: main
          delete-branch: true

      - name: Auto-Merge Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.create-pr.outputs.pull-request-number }},
              merge_method: 'squash'
            })
