name: Update Data
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up R
      uses: r-lib/actions/setup-r@v1

    - name: Update data
      run: Rscript update_report.R

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Generate unique branch name
        BRANCH_NAME="auto/update-covid-$(date +%s)"
        git checkout -B $BRANCH_NAME
        git add .
        git commit -m "Update covid data"
        git push origin $BRANCH_NAME

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update covid data
        title: 'Update covid data'
        body: 'Automated update of covid data'

        branch: $BRANCH_NAME

        base: main
