name: Update COVID Report

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("arrow", "dplyr", "readr", "ggplot2", "lubridate", "knitr", "tidyr"))'

      - name: Run update script
        run: Rscript update_report.R

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md data/*.parquet plots/*.png
          git commit -m "🕒 Auto-update report [$(date)]" || echo "No changes"
          git push
