name: Update Bike Data
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  BRANCH_NAME: auto/update-bike-$(date +%s)

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev
        R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'ggplot2', 'lubridate', 'knitr', 'tidyr', 'arrow', 'plotly', 'DT', 'htmltools'), repos = 'https://cloud.r-project.org')"

    - name: Update data
      run: Rscript update_report.R

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -B ${{ env.BRANCH_NAME }}
        git add .
        git commit -m "Update bike share data and dashboard"
        git push origin ${{ env.BRANCH_NAME }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Update bike share analytics'
        body: 'Automated update of Toronto bike share statistics'
        branch: ${{ env.BRANCH_NAME }}
        base: main
        delete-branch: true
