name: Update Bike Data
on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("httr", "jsonlite", "dplyr", "ggplot2", "lubridate", "knitr", "tidyr", "plotly", "DT", "htmltools", "leaflet", "viridis", "htmlwidgets"))'

      - name: Run R script
        run: Rscript update_report.R

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update bike share dashboard"
          title: "Update bike share dashboard"
          body: "Automated data update"
          branch: "auto/update-bike-${{ github.run_id }}"
          base: main
