name: Update COVID Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ github.workspace }}/R/library

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ runner.os }}-${{ hashFiles('update_report.R') }}
          restore-keys: |
            r-${{ runner.os }}-

      - name: Install dependencies
        run: |
          install.packages(c("arrow", "dplyr", "readr", "ggplot2", "lubridate", "knitr", "tidyr"), repos = "https://cloud.r-project.org")

      - name: Run update script
        run: Rscript update_report.R

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md data/*.parquet plots/*.png
          git commit -m "🕒 Auto-update report [$(date)]" || echo "No changes"
          git push
