name: Update Bike Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.3.0
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libarrow-dev

      - name: Install R packages
        run: |
          R -e "install.packages(c('httr', 'jsonlite', 'lubridate', 'viridis', 'arrow', 'zoo'), repos = 'https://cloud.r-project.org', dependencies = TRUE)"
          
      - name: Run R script
        run: Rscript update_report.R

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update bike share dashboard"
          title: "Update bike share dashboard"
          body: "Automated data update"
          branch: "auto/update-bike-${{ github.run_id }}"
          base: main
          delete-branch: true

      - name: Auto-Merge Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.create-pr.outputs.pull-request-number }},
              merge_method: 'squash'
            })
