name: Update Bike Data
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libgeos-dev libproj-dev
        R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'ggplot2', 'lubridate', 'knitr', 'tidyr', 'arrow'), repos = 'https://cloud.r-project.org')"

    - name: Update data
      run: Rscript update_report.R

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        BRANCH_NAME="auto/update-bike-$(date +%s)"
        git checkout -B $BRANCH_NAME
        git add .
        git commit -m "Update bike share data"
        git push origin $BRANCH_NAME

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        title: 'Update bike share analytics'
        body: 'Automated update of Toronto bike share statistics'
        branch: $BRANCH_NAME
        base: main
